forumController and userController Development
bethel-school-of-technology/team-jsdevstars-backend pull request #21
Opened 2023-01-29 02:10 UTC by ByFaith117

Implemented full forumController functionality (except right now it only checks whether the user is logged in, not whether the user is the one who created the forum). Added a function to log in user. All functions tested on Postman.

2023-01-29 05:52 UTC, Ordervous requested changes
Hi Andrew, I just noticed your index.ts has got localhost instead of the db details
The rest looks pretty good

2023-01-30 22:32 UTC, ByFaith117 commented
Hey Brett, thanks for reviewing the code! Actually, the localhost portion is commented out~ I was using it for testing, figured it would be easier to leave it in the code for future testing. But the functional code still calls the online free database though.

2023-01-31 09:22 UTC, Ordervous commented
Looks good

2023-01-31 09:22 UTC, Ordervous approved these changes

2023-01-31 09:23 UTC, merged